package utils;
// HrefHTTPSAPIDataforsyningenDkPostnumre2200Nr2200NavnKbenhavnNStormodtageradresserNullBbox12524890355681663612572207135571214273Visueltcenter1254914572556940569KommunerHrefHTTPSAPIDataforsyningenDkKommuner0101Kode0101NavnKbenhavnHrefHTTPSAPIDataforsyningenDkKommuner0147Kode0147NavnFrederiksbergNdret20210616T210138265ZGeoNdret20210616T210138265ZGeoVersion8DagiID192200.java

// Generated by https://quicktype.io

import java.util.Map;

public class CityInfoApi {
    private String href;
    private String nr;
    private String navn;
    private Object stormodtageradresser;
    private double[] bbox;
    private double[] visueltcenter;
    private Kommuner[] kommuner;
    private String ndret;
    private String geoNdret;
    private long geoVersion;
    private String dagiID;

    public String getNr() {
        return nr;
    }

    public String getNavn() {
        return navn;
    }


}

// Kommuner.java

class Kommuner {
    private String href;
    private String kode;
    private String navn;

}

